api = "0.2"

[buildpack]
id = "jkutner/null"
version = "1.0.3"
name = "‚êÄ"
homepage = "https://github.com/jkutner/null-cnb"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.buildpacks.samples.stacks.bionic"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

